version: '2'

services:
  opa:
    hostname: opa
    image: openpolicyagent/opa:0.10.6
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--config-file=/config/config.yaml"
      - "--plugin-dir=/plugins"
      - "/policies/api_authz.rego"
    volumes:
      - ./volumes/opa-config/:/config
      - ./volumes/opa-policies/:/policies
      - ./volumes/opa-plugins/:/plugins

  api_server:
    image: openpolicyagent/demo-restful-api:latest
    ports:
      - 5000:5000
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/httpapi/authz

  splunk:
    hostname: splunk
    image: splunk/splunk:7.0.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_ENABLE_LISTEN: 9997
    ports:
      - "8000:8000" # splunk UI
    volumes:
      - "./volumes/splunk-apps/demo_hf:/opt/splunk/etc/apps/demo_hf"
      - "./volumes/splunk-apps/demo_idx:/opt/splunk/etc/apps/demo_idx"
      - "./volumes/splunk-apps/demo_shc:/opt/splunk/etc/apps/demo_shc"

