global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'opa'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
    - targets:
      - 'opa:8181'

